import Head from 'next/head'
import Header from "../Components/Header"
import Navbar from '../Components/Navbar'
import Results from '../Components/Results'
import requests from '../utilities/requests'

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu.png" />
      </Head>
      <Header/>
      <Navbar/>
      <Results results={results}/>
    </div>
  )
}

export const getServerSideProps = async context => {
    const genre = context.query.genre;
    const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)  
    const response = await request.json();
    return {
      props: {
        results: response.results
      }
    }
}

